# Vitenskapsfilosofi


## Oppgave 1 - Hume og induksjonsteorien

* Ifølge Hume er det umulig å rasjonelt begrunne bruken av induksjon. Hva er argumentet for denne konklusjonen? Er det mulig å unngå Humes konklusjon? Begrunn svaret ditt. 

På midten av 1700-tallet presenterte den skotske filosofen David Hume induksjonsproblemet gjennom sine to hovedverk [@rækstad2012]. Selv om lignende diskusjoner allerede fant sted allerede på midten av 1600-tallet, er det Hume som gjorde problemet særlig kjent. Problemet grunner i at induktive slutninger og argumenter ikke er logisk bindende, men heller en antakelse basert på sannsynlighet [@rækstad2012]. Induktive slutninger kan defineres som «en type resonnement eller slutning hvor premissenes sannhet ikke garanterer for konklusjonens sannhet» [@rækstad2012]. Alle sannynlighetsdommer vil være basert på antagelsen om at fremtiden ligner fortiden. Rasjonalitet bygger på fornuft og logikk. Hume, som mener at det er umulig å rasjonelt begrunne bruken av induksjon, peker på bristen som etter hvert vil oppstå mellom sannsynlige antakelser og fornuft og logikk. Et kjent eksempel er at vi antar at solen vi komme opp på himmelen i morgen. Antakelsen baserer vi på den erfaringen av at solen har stått opp hver dag så lenge vi kan huske. Vi finner denne antakelsen også igjen i uniformitetsprinisppet, som baserer seg på at «fremtiden vil være som fortiden» (Vassend, O. B., personlig kommunikasjon, 9. oktober, 2023). Ifølge Hume forutsetter alle induktive argumenter uniformitetsprinisppet. Det betyr at argumentene baserer seg på at siden det har skjedd tidligere, vil det mest sannsynlig skje igjen. Det Hume blant annet belyser er tanken om at det nødvendigvis ikke trenger å skje igjen, gjennom strengt rasjonell begrunnelse [@rækstad2012]. Han mente at selv om vi har observert et fenomen flere ganger, betyr ikke det at det konsekvent vil skje i fremtiden. Dermed stiller Hume spørsmål til den universelle generaliseringen og uniformitetsprinisppet. Siden uniformitetsprinisppet står uten rasjonell begrunnelse, vil ikke heller de induktive argumentene ha en rasjonell begrunnelse. Med andre ord kan ikke rasjonaliteten støtte opp under tanken om at fremtiden vil være som fortiden, ettersom fornuften og logikken tilsier at det på et tidspunkt ikke lenger kan stemme. Hume mener derfor at de induktive slutningene ikke er en pålitelig kilde til kunnskap, siden vi ikke vet om slutningen kan være gyldig til evig tid [@hempel1966]. 

Innenfor filosofien har denne problemstillingen vært sentral siden Hume gjorde den kjent på midten av 1800-tallet. Hume sitt svar på hvorfor vi velger å betro oss til disse argumentene er vår psykologiske sammenheng (Vassend, O. B., personlig kommunikasjon, 9. oktober, 2023). 

Den rasjonelle begrunnelsen baserer seg på fornuft og logikk, og man skulle tro at logikken og fornuften skulle tilsi at det som tidligere har skjedd ville skje igjen. Likevel sier Humes strenge tolkning av rasjonalitet mot dette. Siden induksjonsproblemet har utfordret induktive slutninger, har det åpnet for andre tilnærminger innenfor vitenskapelig metode. Både sannsynlighetsteori innenfor Bayesianisme, HD-teorien og falsifikasjonisme er alle teorier som tilnærmer seg induktive slutninger, med ulik grad av rasjonell begrunnelse (Vassend, O. B., personlig kommunikasjon, 9. oktober, 2023). Med disse tilnærmingene vil vi kunne angripe argumenter på en mer deduktiv måte. Logikken og logiske prinsipper vil i større grad bidra til å kunne trekke slutninger. På denne måten kan man til en viss grad unngå Humes konklusjon. Det er likevel vanskelig å si om den alltid vil være totalt fraværende, eller om den alltid kan brukes til å stille spørsmål ved induktive slutninger.


## Oppgave 2 - Falsifikasjonisme

* Gi en kort beskrivelse og forklaring av falsifikasjonisme. Presenter så et problem med denne teorien. Tror du problemet kan løses? Begrunn svaret ditt. 

Falsifikasjonisme er innenfor vitenskapsfilosofien et begrep som baserer seg på at man påviser om en teori er usann eller uholdbar [@alnes2023a]. Begrepet ble særlig kjent gjennom Karl Popper, en østerriksk-britisk filosof som levde på 1900-tallet. Falsifikasjonisme viser hvordan en hypotese eller et utsagn må være formulert slik at det kan bli bevist feil gjennom eksperimenter eller observasjoner. [@popper1969] legger også dette til grunn når han skiller mellom vitenskapelige og uvitenskapelige teorier. Han mente at mye ble allment akseptert på bakgrunn av sin empiriske metode, som i stor grad var induktiv basert på observasjon eller eksperiment. Dette var noe han motsatte seg, da han ofte søkte etter å skille mellom genuint empirisk metode, ikke-empiriske metode og pseudo-empirisk metode [@popper1969]. Det han da sto igjen med var en metode som ikke oppfylte de vitenskapelige standarder han mente var essensielle for god vitenskap [@popper1969]. Dermed utfordret han de induktive antagelsene basert på observasjon eller eksperiment, ettersom at hypoteser og antagelser måtte fremlegges på en slik måte at de kan bli falsifisert. Han mente videre at dersom en teori motbevises, må den endres eller forkastes [@popper1969]. For å eksemplifisere dette kan vi se til hvordan det er allment akseptert hvordan alle ravner er sorte. Denne påstanden blir falsifisert dersom vi finner en ravn som ikke er sort [@alnes2023a]. Dersom noen skulle observere en sort ravn er påstanden falsifisert, og den må bli revidert eller forkastet. På denne måten er påstanden falsifiserbar, og dermed vitenskapelig i følge Popper selv. [@popper1969] mente på sin side at det er gjennom falsifikasjon at kunnskapen utviklet seg. 

Denne tilnærmingen byr på flere problemer. Et av problemene er at tilnærminger er såpass bastant at den sier «en påstand er vitenskapelig hvis, og bare hvis den er falsifiserbar» (Vassend, O. B, personlig kommunikasjon, 10. oktober, 2023). Dette byr på utfordringer, ettersom at blant annet enkelte sannsynlighetspåstander ikke er falsifiserbare. Dette bunner i deres formulering og kontekst. Dersom påstanden bygger på det generelle og ikke er knyttet til spesifikk empiri eller observasjon, kan påstanden være vanskelig å falsifisere. Et eksempel her kan være påstanden om at «det er sannsynlig at det vil snø i morgen». Dette er vanskelig å falsifisere ettersom det er basert på en sannsynlighet, og ikke en observasjon. Ser vi derimot på spesifikke sannynlighetsutsagn der utsagnet er knyttet til en bestemt hendelse eller observasjon kan den lettere være falsifiserbar. 

Problematikken rundt falsifisering skiller seg i stor grad fra blant annet den bayesianske tilnærmingen, som tar hensyn til usikkerhet og graden av pålitelighet basert på observasjoner og eksperimenter [@godfrey-smith2003]. En måte å «løse» problemet på er å kombinere falsifikasjonisme og bayesianiske sannsynlighetsberegningen. På denne måten kan man få en mer balansert tilnærming, ettersom som at man både kan teste teorien på en streng måte og vurdere sannsynligheten av om den er sann eller ikke.